namespace DB_Data.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class initV3 : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.Addresses", "Customer_id", "dbo.Customers");
            DropForeignKey("dbo.Addresses", "Seller_id", "dbo.Sellers");
            DropForeignKey("dbo.Addresses", "Shipper_id", "dbo.Shippers");
            DropForeignKey("dbo.Cards", "Customer_id", "dbo.Customers");
            DropForeignKey("dbo.Carts", "Customer_id", "dbo.Customers");
            DropForeignKey("dbo.Phones", "Customer_id", "dbo.Customers");
            DropForeignKey("dbo.Cards", "Seller_id", "dbo.Sellers");
            DropForeignKey("dbo.Cards", "Shipper_id", "dbo.Shippers");
            DropForeignKey("dbo.Phones", "Seller_id", "dbo.Sellers");
            DropForeignKey("dbo.Phones", "Shipper_id", "dbo.Shippers");
            DropForeignKey("dbo.Carts", "Products_id", "dbo.Products");
            DropForeignKey("dbo.Orders", "product_id", "dbo.Products");
            DropIndex("dbo.Addresses", new[] { "Customer_id" });
            DropIndex("dbo.Addresses", new[] { "Seller_id" });
            DropIndex("dbo.Addresses", new[] { "Shipper_id" });
            DropIndex("dbo.Cards", new[] { "Customer_id" });
            DropIndex("dbo.Cards", new[] { "Seller_id" });
            DropIndex("dbo.Cards", new[] { "Shipper_id" });
            DropIndex("dbo.Phones", new[] { "Customer_id" });
            DropIndex("dbo.Phones", new[] { "Seller_id" });
            DropIndex("dbo.Phones", new[] { "Shipper_id" });
            DropIndex("dbo.Carts", new[] { "Customer_id" });
            DropIndex("dbo.Carts", new[] { "Products_id" });
            DropIndex("dbo.Orders", new[] { "product_id" });
            DropIndex("dbo.OrderSummaries", new[] { "customerid" });
            RenameColumn(table: "dbo.Addresses", name: "Customer_id", newName: "CustomerID");
            RenameColumn(table: "dbo.Addresses", name: "Seller_id", newName: "SellerID");
            RenameColumn(table: "dbo.Addresses", name: "Shipper_id", newName: "ShipperID");
            RenameColumn(table: "dbo.Cards", name: "Customer_id", newName: "CustomerID");
            RenameColumn(table: "dbo.Carts", name: "Customer_id", newName: "CustomerID");
            RenameColumn(table: "dbo.Likes", name: "Customer_id", newName: "CustomerID");
            RenameColumn(table: "dbo.Phones", name: "Customer_id", newName: "CustomerID");
            RenameColumn(table: "dbo.Reviews", name: "Customer_id", newName: "CustomerID");
            RenameColumn(table: "dbo.Wishlists", name: "Customers_id", newName: "CustomerID");
            RenameColumn(table: "dbo.Cards", name: "Seller_id", newName: "SellerID");
            RenameColumn(table: "dbo.Cards", name: "Shipper_id", newName: "ShipperID");
            RenameColumn(table: "dbo.Phones", name: "Seller_id", newName: "SellerID");
            RenameColumn(table: "dbo.Products", name: "Sellers_id", newName: "SellerID");
            RenameColumn(table: "dbo.Phones", name: "Shipper_id", newName: "ShipperID");
            RenameColumn(table: "dbo.Carts", name: "Products_id", newName: "ProductID");
            RenameColumn(table: "dbo.Products", name: "Category_id", newName: "CategoryID");
            RenameColumn(table: "dbo.Likes", name: "Product_id", newName: "ProductID");
            RenameColumn(table: "dbo.Orders", name: "product_id", newName: "ProductID");
            RenameColumn(table: "dbo.Reviews", name: "Product_id", newName: "ProductID");
            RenameColumn(table: "dbo.Wishlists", name: "Product_id", newName: "ProductID");
            RenameColumn(table: "dbo.OrderSummaries", name: "Shipper_id", newName: "ShipperID");
            RenameIndex(table: "dbo.Products", name: "IX_Sellers_id", newName: "IX_SellerID");
            RenameIndex(table: "dbo.Products", name: "IX_Category_id", newName: "IX_CategoryID");
            RenameIndex(table: "dbo.Likes", name: "IX_Customer_id", newName: "IX_CustomerID");
            RenameIndex(table: "dbo.Likes", name: "IX_Product_id", newName: "IX_ProductID");
            RenameIndex(table: "dbo.OrderSummaries", name: "IX_Shipper_id", newName: "IX_ShipperID");
            RenameIndex(table: "dbo.Reviews", name: "IX_Customer_id", newName: "IX_CustomerID");
            RenameIndex(table: "dbo.Reviews", name: "IX_Product_id", newName: "IX_ProductID");
            RenameIndex(table: "dbo.Wishlists", name: "IX_Customers_id", newName: "IX_CustomerID");
            RenameIndex(table: "dbo.Wishlists", name: "IX_Product_id", newName: "IX_ProductID");
            AlterColumn("dbo.Addresses", "CustomerID", c => c.Int(nullable: true));
            AlterColumn("dbo.Addresses", "SellerID", c => c.Int(nullable: true));
            AlterColumn("dbo.Addresses", "ShipperID", c => c.Int(nullable: true));
            AlterColumn("dbo.Cards", "CustomerID", c => c.Int(nullable: true));
            AlterColumn("dbo.Cards", "SellerID", c => c.Int(nullable: true));
            AlterColumn("dbo.Cards", "ShipperID", c => c.Int(nullable: true));
            AlterColumn("dbo.Phones", "CustomerID", c => c.Int(nullable: true));
            AlterColumn("dbo.Phones", "SellerID", c => c.Int(nullable: true));
            AlterColumn("dbo.Phones", "ShipperID", c => c.Int(nullable: true));
            AlterColumn("dbo.Carts", "CustomerID", c => c.Int(nullable: false));
            AlterColumn("dbo.Carts", "ProductID", c => c.Int(nullable: false));
            AlterColumn("dbo.Orders", "ProductID", c => c.Int(nullable: false));
            CreateIndex("dbo.Addresses", "CustomerID");
            CreateIndex("dbo.Addresses", "SellerID");
            CreateIndex("dbo.Addresses", "ShipperID");
            CreateIndex("dbo.Cards", "CustomerID");
            CreateIndex("dbo.Cards", "SellerID");
            CreateIndex("dbo.Cards", "ShipperID");
            CreateIndex("dbo.Phones", "CustomerID");
            CreateIndex("dbo.Phones", "SellerID");
            CreateIndex("dbo.Phones", "ShipperID");
            CreateIndex("dbo.Carts", "CustomerID");
            CreateIndex("dbo.Carts", "ProductID");
            CreateIndex("dbo.Orders", "ProductID");
            CreateIndex("dbo.OrderSummaries", "CustomerID");
            AddForeignKey("dbo.Addresses", "CustomerID", "dbo.Customers", "id", cascadeDelete: true);
            AddForeignKey("dbo.Addresses", "SellerID", "dbo.Sellers", "id", cascadeDelete: true);
            AddForeignKey("dbo.Addresses", "ShipperID", "dbo.Shippers", "id", cascadeDelete: true);
            AddForeignKey("dbo.Cards", "CustomerID", "dbo.Customers", "id", cascadeDelete: true);
            AddForeignKey("dbo.Carts", "CustomerID", "dbo.Customers", "id", cascadeDelete: true);
            AddForeignKey("dbo.Phones", "CustomerID", "dbo.Customers", "id", cascadeDelete: true);
            AddForeignKey("dbo.Cards", "SellerID", "dbo.Sellers", "id", cascadeDelete: true);
            AddForeignKey("dbo.Cards", "ShipperID", "dbo.Shippers", "id", cascadeDelete: true);
            AddForeignKey("dbo.Phones", "SellerID", "dbo.Sellers", "id", cascadeDelete: true);
            AddForeignKey("dbo.Phones", "ShipperID", "dbo.Shippers", "id", cascadeDelete: true);
            AddForeignKey("dbo.Carts", "ProductID", "dbo.Products", "id", cascadeDelete: true);
            AddForeignKey("dbo.Orders", "ProductID", "dbo.Products", "id", cascadeDelete: true);
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.Orders", "ProductID", "dbo.Products");
            DropForeignKey("dbo.Carts", "ProductID", "dbo.Products");
            DropForeignKey("dbo.Phones", "ShipperID", "dbo.Shippers");
            DropForeignKey("dbo.Phones", "SellerID", "dbo.Sellers");
            DropForeignKey("dbo.Cards", "ShipperID", "dbo.Shippers");
            DropForeignKey("dbo.Cards", "SellerID", "dbo.Sellers");
            DropForeignKey("dbo.Phones", "CustomerID", "dbo.Customers");
            DropForeignKey("dbo.Carts", "CustomerID", "dbo.Customers");
            DropForeignKey("dbo.Cards", "CustomerID", "dbo.Customers");
            DropForeignKey("dbo.Addresses", "ShipperID", "dbo.Shippers");
            DropForeignKey("dbo.Addresses", "SellerID", "dbo.Sellers");
            DropForeignKey("dbo.Addresses", "CustomerID", "dbo.Customers");
            DropIndex("dbo.OrderSummaries", new[] { "CustomerID" });
            DropIndex("dbo.Orders", new[] { "ProductID" });
            DropIndex("dbo.Carts", new[] { "ProductID" });
            DropIndex("dbo.Carts", new[] { "CustomerID" });
            DropIndex("dbo.Phones", new[] { "ShipperID" });
            DropIndex("dbo.Phones", new[] { "SellerID" });
            DropIndex("dbo.Phones", new[] { "CustomerID" });
            DropIndex("dbo.Cards", new[] { "ShipperID" });
            DropIndex("dbo.Cards", new[] { "SellerID" });
            DropIndex("dbo.Cards", new[] { "CustomerID" });
            DropIndex("dbo.Addresses", new[] { "ShipperID" });
            DropIndex("dbo.Addresses", new[] { "SellerID" });
            DropIndex("dbo.Addresses", new[] { "CustomerID" });
            AlterColumn("dbo.Orders", "ProductID", c => c.Int());
            AlterColumn("dbo.Carts", "ProductID", c => c.Int());
            AlterColumn("dbo.Carts", "CustomerID", c => c.Int());
            AlterColumn("dbo.Phones", "ShipperID", c => c.Int());
            AlterColumn("dbo.Phones", "SellerID", c => c.Int());
            AlterColumn("dbo.Phones", "CustomerID", c => c.Int());
            AlterColumn("dbo.Cards", "ShipperID", c => c.Int());
            AlterColumn("dbo.Cards", "SellerID", c => c.Int());
            AlterColumn("dbo.Cards", "CustomerID", c => c.Int());
            AlterColumn("dbo.Addresses", "ShipperID", c => c.Int());
            AlterColumn("dbo.Addresses", "SellerID", c => c.Int());
            AlterColumn("dbo.Addresses", "CustomerID", c => c.Int());
            RenameIndex(table: "dbo.Wishlists", name: "IX_ProductID", newName: "IX_Product_id");
            RenameIndex(table: "dbo.Wishlists", name: "IX_CustomerID", newName: "IX_Customers_id");
            RenameIndex(table: "dbo.Reviews", name: "IX_ProductID", newName: "IX_Product_id");
            RenameIndex(table: "dbo.Reviews", name: "IX_CustomerID", newName: "IX_Customer_id");
            RenameIndex(table: "dbo.OrderSummaries", name: "IX_ShipperID", newName: "IX_Shipper_id");
            RenameIndex(table: "dbo.Likes", name: "IX_ProductID", newName: "IX_Product_id");
            RenameIndex(table: "dbo.Likes", name: "IX_CustomerID", newName: "IX_Customer_id");
            RenameIndex(table: "dbo.Products", name: "IX_CategoryID", newName: "IX_Category_id");
            RenameIndex(table: "dbo.Products", name: "IX_SellerID", newName: "IX_Sellers_id");
            RenameColumn(table: "dbo.OrderSummaries", name: "ShipperID", newName: "Shipper_id");
            RenameColumn(table: "dbo.Wishlists", name: "ProductID", newName: "Product_id");
            RenameColumn(table: "dbo.Reviews", name: "ProductID", newName: "Product_id");
            RenameColumn(table: "dbo.Orders", name: "ProductID", newName: "product_id");
            RenameColumn(table: "dbo.Likes", name: "ProductID", newName: "Product_id");
            RenameColumn(table: "dbo.Products", name: "CategoryID", newName: "Category_id");
            RenameColumn(table: "dbo.Carts", name: "ProductID", newName: "Products_id");
            RenameColumn(table: "dbo.Phones", name: "ShipperID", newName: "Shipper_id");
            RenameColumn(table: "dbo.Products", name: "SellerID", newName: "Sellers_id");
            RenameColumn(table: "dbo.Phones", name: "SellerID", newName: "Seller_id");
            RenameColumn(table: "dbo.Cards", name: "ShipperID", newName: "Shipper_id");
            RenameColumn(table: "dbo.Cards", name: "SellerID", newName: "Seller_id");
            RenameColumn(table: "dbo.Wishlists", name: "CustomerID", newName: "Customers_id");
            RenameColumn(table: "dbo.Reviews", name: "CustomerID", newName: "Customer_id");
            RenameColumn(table: "dbo.Phones", name: "CustomerID", newName: "Customer_id");
            RenameColumn(table: "dbo.Likes", name: "CustomerID", newName: "Customer_id");
            RenameColumn(table: "dbo.Carts", name: "CustomerID", newName: "Customer_id");
            RenameColumn(table: "dbo.Cards", name: "CustomerID", newName: "Customer_id");
            RenameColumn(table: "dbo.Addresses", name: "ShipperID", newName: "Shipper_id");
            RenameColumn(table: "dbo.Addresses", name: "SellerID", newName: "Seller_id");
            RenameColumn(table: "dbo.Addresses", name: "CustomerID", newName: "Customer_id");
            CreateIndex("dbo.OrderSummaries", "customerid");
            CreateIndex("dbo.Orders", "product_id");
            CreateIndex("dbo.Carts", "Products_id");
            CreateIndex("dbo.Carts", "Customer_id");
            CreateIndex("dbo.Phones", "Shipper_id");
            CreateIndex("dbo.Phones", "Seller_id");
            CreateIndex("dbo.Phones", "Customer_id");
            CreateIndex("dbo.Cards", "Shipper_id");
            CreateIndex("dbo.Cards", "Seller_id");
            CreateIndex("dbo.Cards", "Customer_id");
            CreateIndex("dbo.Addresses", "Shipper_id");
            CreateIndex("dbo.Addresses", "Seller_id");
            CreateIndex("dbo.Addresses", "Customer_id");
            AddForeignKey("dbo.Orders", "product_id", "dbo.Products", "id");
            AddForeignKey("dbo.Carts", "Products_id", "dbo.Products", "id");
            AddForeignKey("dbo.Phones", "Shipper_id", "dbo.Shippers", "id");
            AddForeignKey("dbo.Phones", "Seller_id", "dbo.Sellers", "id");
            AddForeignKey("dbo.Cards", "Shipper_id", "dbo.Shippers", "id");
            AddForeignKey("dbo.Cards", "Seller_id", "dbo.Sellers", "id");
            AddForeignKey("dbo.Phones", "Customer_id", "dbo.Customers", "id");
            AddForeignKey("dbo.Carts", "Customer_id", "dbo.Customers", "id");
            AddForeignKey("dbo.Cards", "Customer_id", "dbo.Customers", "id");
            AddForeignKey("dbo.Addresses", "Shipper_id", "dbo.Shippers", "id");
            AddForeignKey("dbo.Addresses", "Seller_id", "dbo.Sellers", "id");
            AddForeignKey("dbo.Addresses", "Customer_id", "dbo.Customers", "id");
        }
    }
}
